import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Providers} from "@/redux/provider";
import {config} from '@fortawesome/fontawesome-svg-core'
import {Amatic_SC} from "next/font/google";
config.autoAddCss = false

import {library} from '@fortawesome/fontawesome-svg-core'
import {fas} from '@fortawesome/free-solid-svg-icons'

library.add(fas);
const amatic = Amatic_SC({
    weight: ["400", "700"],
    subsets: ['latin'],
    display: 'swap',
})
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  className={amatic.className}>
      <body className="app">
		<Providers>
			{children}
		</Providers>
	  </body>
    </html>
  )
}
